/*
 @name : 锅巴汉化 - Web汉化插件
 @author : 麦子、JAR、小蓝、好阳光的小锅巴、人民當家做主
 @version : V0.6.1 - 2026-5-26
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737
*/

// ============================================================
// 匹配配置
// ============================================================
// ignoreCase: true   忽略大小写(Gold/gold/GOLD都匹配), false=区分大小写
// trimSpaces: true   忽略首尾空格(" gold "匹配"gold"), false=保留空格
//
// 影响范围：
//   ✅ cnItems 精确匹配(字符串值+数组值)
//   ✅ cnItems 分类索引({{分类名}}/{{分类名*}}/{{分类名*|sep|join}})
//   ✅ cnResourceNames 名词翻译
//   ✅ cnPrefix / cnPostfix 前后缀
//   ✅ cnRegReplace / 排除规则 / 模板正则(通过 addIgnoreCaseFlag / cnConfig.ignoreCase 控制)
var cnConfig = {
    ignoreCase: true,
    trimSpaces: true,
};

// ============================================================
// cnCategoriesList — 分类名称注册表（供编辑器工具使用）
// ============================================================
// 分类数据由 cnItems 中的数组值 ["译文", "分类名"] 自动构建。
// 此列表仅声明有哪些分类，以便编辑器提供分类选择/管理功能。
var cnCategoriesList = [
    "resource",
    "item",
];

// ============================================================
// cnItems — 主要翻译词条
// ============================================================
// 用法：
//   "原文": "译文"                         → 精确静态匹配
//   "原文": ["译文", "分类名"]               → 静态匹配 + 自动加入分类
//   "Cost: {{0}}": "消耗：{{0}}"            → 模板匹配 ({{0}} 匹配任意值)
//   "{{resource}}: {{%d}}": "{{resource}}：{{%d}}"  → 分类模板 + 数字验证
//   "{{分类名*}}": 仅在该分类查找，找不到保留原文
//   "{{分类名*|sep|join}}": 分类限定列表解析
//   "{{*}}": 通用列表，逐项递归翻译
//   "{{*|sep|join}}": 自定义分隔符/连接词的列表
// ============================================================
var cnItems = {
    // --- 静态匹配 ---
    "Welcome": "欢迎",
    "Score": "分数",
    "Health Potion": "生命药水",
    "Hello World": "你好世界",

    // --- 分类词条 [译文, 分类名] ---
    "gold": ["金币", "resource"],
    "wood": ["木材", "resource"],
    "stone": ["石头", "resource"],
    "iron": ["铁", "resource"],
    "sword": ["剑", "item"],
    "shield": ["盾牌", "item"],
    "helmet": ["头盔", "item"],

    // --- 模板 ({{0}} / {{1}}) ---
    "Cost: {{0}}": "消耗：{{0}}",
    "Next Improvement: {{0}}": "下次提升：{{0}}",
    "Wanderer {{0}}": "流浪者 {{0}}",
    "Descender {{0}}": "降临者 {{0}}",
    "Abyssal {{0}}": "深渊 {{0}}",
    "Initiate {{0}}": "启动 {{0}}",
    "Spelunker {{0}}": "探险者 {{0}}",
    "Level {{0}}": "等级 {{0}}",
    "{{0}} x {{1}}": "{{0}} × {{1}}",

    // --- 模板 ({{分类名}} + {{%d}}) ---
    "{{resource}}: {{0}}": "{{resource}}：{{0}}",

    // --- 模板 ({{分类名*}} 仅分类) ---
    "Get {{0}} {{resource*}}": "获得 {{0}} {{resource*}}",

    // --- 模板 ({{分类名*|sep|join}} 分类列表) ---
    "Craft {{item*|,|和}}": "制作{{item*|,|和}}",

    // --- 通用列表 {{*}} / {{*|sep|join}} ---
    "Items: {{*}}": "物品：{{*}}",
    "Mats: {{*|, |、}}": "材料：{{*|, |、}}",

    // --- 数字占位符 {{%d}} ---
    "Room {{%d}}": "房间 {{%d}}",
    "T{{%d}}": "T{{%d}}",
    "+{{%d}}/s · {{%d}}g": "+{{%d}}/秒 · {{%d}} 金币",
    "+{{%d}} g/s · {{%d}}g": "+{{%d}} 金币/秒 · {{%d}} 金币",
    "+{{%d}} g/kill · {{%d}}g": "+{{%d}} 金币/击杀 · {{%d}} 金币",
    "+{{%d}}g/min · {{%d}}g": "+{{%d}} 金币/分钟 · {{%d}} 金币",
    "+{{%d}}% steal · {{%d}}g": "+{{%d}}% 偷取 · {{%d}} 金币",
    "+{{%d}}% dodge · {{%d}}g": "+{{%d}}% 闪避 · {{%d}} 金币",
    "+{{%d}}% pen · {{%d}}g": "+{{%d}}% 抵抗 · {{%d}} 金币",
    "+×{{%d}} crit · {{%d}}g": "+×{{%d}} 暴击 · {{%d}} 金币",
    "+{{%d}} DMG · {{%d}}g": "+{{%d}} 伤害 · {{%d}} 金币",
    "+{{%d}} min · {{%d}}g": "+{{%d}} 分钟 · {{%d}} 金币",
    "+{{%d}} HP · {{%d}}g": "+{{%d}} 生命值 · {{%d}} 金币",
    "+{{%d}} ARM · {{%d}}g": "+{{%d}} 护甲 · {{%d}} 金币",
    "+{{%d}}% crit · {{%d}}g": "+{{%d}}% 暴击 · {{%d}} 金币",
    "+{{%d}}% shld · {{%d}}g": "+{{%d}}% 护盾 · {{%d}} 金币",
    "+{{%d}} % · {{%d}}g": "+{{%d}} % · {{%d}} 金币",
    "Common Copper Ring Lvl.{{%d}}": "普通 铁戒指 等级 {{%d}}",
    "Uncommon Copper Ring Lvl.{{%d}}": "罕见 铁戒指 等级 {{%d}}",
    "Uncommon Leather Cord Lvl.{{%d}}": "罕见 皮绳 等级 {{%d}}",
    "Buy {{%d}} passive upgrades": "购买 {{%d}} 被动升级",
    "Ring {{%d}}": "戒指 {{%d}}",
    "Clear {{%d}} rooms": "清理 {{%d}} 房间",
    "Defeat {{%d}} elites": "击败 {{%d}} 精英",
    "Defeat {{%d}} bosses": "击败 {{%d}} Boss",
    "Equip → Ring {{%d}}": "装备 → 戒指 {{%d}}",
    "Reach Room {{%d}} in Tier {{%d}}": "到达房间 {{%d}} 在第 {{%d}} 关中",
    "{{%d}}g": "{{%d}} 金币",
    "{{%d}}k": "{{%d}}k",
    "{{%d}}m": "{{%d}}m",
    "{{%d}} min": "{{%d}} 分钟",
    "HP: {{%d}}": "生命值：{{%d}}",
    "DMG: {{%d}}": "伤害：{{%d}}",

    "222":"222",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "Arms":"胳膊",
    "Dark Knight":"暗黑骑士",
    "Neck":"项链",
    "Off-Hand":"副手",
    "SWARM ":"蜂群",
    "Bandit":"强盗",
    " Affixes":"词缀",
    "neck":"项链",
    "Area cleared — next threat incoming":"区域已肃清，新的威胁即将来袭",
    "Armor":"护甲",
    "Combat":"战斗",
    "Damage":"伤害",
    "DMG · Strike":"伤害·重击",
    "Equipped":"已装备",
    "g/kill":"每击杀收益",
    "Gear":"装备",
    "Gold":"金币",
    "Health":"生命值",
    "max":"上限",
    "Next":"下一个",
    "Passives":"被动能力",
    "Stash":"储物栏",
    "Stash empty":"储物栏为空",
    "Stats":"属性",
    "XP":"经验值",
    "Your character attacks automatically. Use the Strike button at the bottom of the screen for bonus manual damage.":"角色会自动攻击，点击屏幕底部重击按钮可额外造成手动伤害",
    "DMG":"伤害",
    "Slime":"史莱姆",
    "Items drop as you fight. Open the Gear tab to equip them and grow stronger.":"战斗中会掉落物品，前往装备界面穿戴来提升战力",
    "Begin":"开始",
    "Defeat enemies to earn Gold. Spend it in the Passives tab to permanently upgrade your power.":"击败敌人获取金币，在被动界面消耗金币永久强化自身",
    "% /kill":"击杀加成百分比",
    "% crit":"暴击率",
    "% DMG":"伤害增幅百分比",
    "% dodge":"闪避率",
    "% pen":"穿透百分比",
    "Armor Pen %":"护甲穿透百分比",
    "Attack Speed":"攻击速度",
    "crit":"暴击",
    "Crit Chance":"暴击几率",
    "Crit Damage":"暴击伤害",
    "Evasion":"闪避",
    "Gold Income":"金币收益",
    "Gold/Kill":"每击杀金币",
    "Item Armor":"装备护甲",
    "Item Damage":"装备伤害",
    "Item Health":"装备生命值",
    "Items":"物品",
    "Lifesteal":"吸血",
    "Offense":"攻击属性",
    "Offline Duration":"离线时长",
    "Offline Gold":"离线金币",
    "Shield on Kill":"击杀获护盾",
    "Strike Damage":"重击伤害",
    "Survivability":"生存能力",
    "Utility":"功能效果",
    "Goblin":"哥布林",
    "Level":"等级",
    "Ring":"戒指",
    "Sell ":"出售",
    " Max Health":"最大生命值",
    "Compare":"对比",
    "Item Stats":"物品属性",
    "Max Health":"最大生命值",
    "Sell for ":"出售可得",
    "Stat Changes":"属性变化",
    "empty slot":"空槽",
    "ring":"戒指",
    " each":" 每个",
    " Return":" 返回",
    "Abyss":"深渊",
    "Blood Moon":"血月",
    "Dark":"深色",
    "Light":"浅色",
    "Themes":"主题",
    "Shop":"商店",
    "Achievements":"成就",
    "Claim":"领取",
    "Locked":"未解锁",
    "Ascendant":"飞升者",
    "Gilded":"鎏金",
    "Oblivion":"湮灭",
    "🏆 Room 2500":"🏆 第2500层",
    "Abyss Runner":"深渊疾行者",
    "Abyss Walker":"深渊行者",
    "Blademaster":"剑术大师",
    "Bloodthirsty":"嗜血者",
    "Boss Slayer":"首领猎杀者",
    "Dedicated":"专注者",
    "Devoted":"虔信者",
    "Elite Hunter":"精英猎手",
    "Fanatic":"狂信徒",
    "Fill every gear slot":"填满所有装备栏",
    "Find your first Celestial item":"获得第一件天界装备",
    "Find your first Exotic":"获得第一件异域装备",
    "Find your first Void item":"获得第一件虚空装备",
    "Ghost":"幽魂",
    "Invested":"已投入",
    "Lucky Find":"幸运拾取",
    "Max out Attack Speed (Lv 225)":"攻击速度升至满级（225级）",
    "Max out Evasion (Lv 100)":"闪避升至满级（100级）",
    "Max out Lifesteal (Lv 100)":"吸血升至满级（100级）",
    "Max out Offline Cap (Lv 48)":"离线收益上限升至满级（48级）",
    "Milestones":"里程碑",
    "Obsessed":"痴迷者",
    "Offline King":"离线王者",
    "Passive Grinder":"被动刷取达人",
    "Repeatable":"可重复挑战",
    "Starborn":"星界之子",
    "Void-Touched":"虚空浸染者",
    "Well Equipped":"装备精良",
    " Full Wipe":"彻底重置",
    " Reset All Progress":"重置全部进度",
    "Also wipes gems and theme. Use for a true fresh start.":"同时清空宝石与外观，彻底重新开始",
    "Auto Sell":"自动出售",
    "Cloud Save":"云存档",
    "Cloud saves active":"云存档已启用",
    "Connected":"已连接",
    "Danger Zone":"危险区域",
    "Get Code":"获取码",
    "Import":"导入",
    "Items of enabled rarities are automatically sold for gold as you descend.":"下落过程中，已开启品级的物品会自动售出换取金币",
    "Move your save to another device. Generate a code here, then enter it on the other device.":"跨设备转移存档。在此生成代码，再于其他设备输入即可",
    "Permanently wipes all progress, gold, passives, gear, and stash. This cannot be undone.":"永久清除所有进度、金币、被动属性、装备及储物栏内容，操作不可撤销",
    "Save Transfer":"存档转移",
    "Unequip":"卸下装备",
    "Wolf":"狼",
    "":"",
    "":"",
    "":"",
    "dps":"dps",
    "Lv":"等级",
    "Lv.":"等级",
    "HP":"生命值",
    "g/s":"金币/每秒",
    "g/min offline":"金币/分钟 离线",
    "/s":"/秒",
    "":"",
    "":"",
    "":"",
    "":"",
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    
};
// ============================================================
// cnResourceNames — 资源名词翻译（备用，优先级低于 cnItems）
// ============================================================
// 支持 "名词: 数值" 格式的自动翻译（如 "Mana: 500" → "法力：500"）
var cnResourceNames = {};
// cnRegReplace — 正则替换（备用，优先级低于精确匹配但高于模板/分类）
var cnRegReplace = new Map([]);
// 前缀/后缀提取（备用）
var cnPrefix = {};
var cnPostfix = {};
// 排除规则（备用）
var cnExcludeWhole = [];
var cnExcludePostfix = [];
