/*
 @name : 锅巴汉化 - Web汉化插件
 @author : 麦子、JAR、小蓝、好阳光的小锅巴、人民當家做主
 @version : V0.6.1 - 2026-5-26
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737
*/

// ============================================================
// 匹配配置
// ============================================================
// ignoreCase: true   忽略大小写(Gold/gold/GOLD都匹配), false=区分大小写
// trimSpaces: true   忽略首尾空格(" gold "匹配"gold"), false=保留空格
//
// 影响范围：
//   ✅ cnItems 精确匹配(字符串值+数组值)
//   ✅ cnItems 分类索引({{分类名}}/{{分类名*}}/{{分类名*|sep|join}})
//   ✅ cnResourceNames 名词翻译
//   ✅ cnPrefix / cnPostfix 前后缀
//   ✅ cnRegReplace / 排除规则 / 模板正则(通过 addIgnoreCaseFlag / cnConfig.ignoreCase 控制)
var cnConfig = {
    ignoreCase: true,
    trimSpaces: true,
};

// ============================================================
// cnCategoriesList — 分类名称注册表（供编辑器工具使用）
// ============================================================
// 分类数据由 cnItems 中的数组值 ["译文", "分类名"] 自动构建。
// 此列表仅声明有哪些分类，以便编辑器提供分类选择/管理功能。
var cnCategoriesList = [
    "resource",
    "item",
];

// ============================================================
// cnItems — 主要翻译词条
// ============================================================
// 用法：
//   "原文": "译文"                         → 精确静态匹配
//   "原文": ["译文", "分类名"]               → 静态匹配 + 自动加入分类
//   "Cost: {{0}}": "消耗：{{0}}"            → 模板匹配 ({{0}} 匹配任意值)
//   "{{resource}}: {{%d}}": "{{resource}}：{{%d}}"  → 分类模板 + 数字验证
//   "{{分类名*}}": 仅在该分类查找，找不到保留原文
//   "{{分类名*|sep|join}}": 分类限定列表解析
//   "{{*}}": 通用列表，逐项递归翻译
//   "{{*|sep|join}}": 自定义分隔符/连接词的列表
// ============================================================
var cnItems = {
    // --- 静态匹配 ---
    "Welcome": "欢迎",
    "Score": "分数",
    "Health Potion": "生命药水",
    "Hello World": "你好世界",

    // --- 分类词条 [译文, 分类名] ---
    "gold": ["金币", "resource"],
    "wood": ["木材", "resource"],
    "stone": ["石头", "resource"],
    "iron": ["铁", "resource"],
    "sword": ["剑", "item"],
    "shield": ["盾牌", "item"],
    "helmet": ["头盔", "item"],

    // --- 模板 ({{0}} / {{1}}) ---
    "Cost: {{0}}": "消耗：{{0}}",
    "Next Improvement: {{0}}": "下次提升：{{0}}",
    "Wanderer {{0}}": "流浪者 {{0}}",
    "Descender {{0}}": "降临者 {{0}}",
    "Abyssal {{0}}": "深渊 {{0}}",
    "Initiate {{0}}": "启动 {{0}}",
    "Spelunker {{0}}": "探险者 {{0}}",
    "Level {{0}}": "等级 {{0}}",
    "{{0}} x {{1}}": "{{0}} × {{1}}",

    // --- 模板 ({{分类名}} + {{%d}}) ---
    "{{resource}}: {{0}}": "{{resource}}：{{0}}",

    // --- 模板 ({{分类名*}} 仅分类) ---
    "Get {{0}} {{resource*}}": "获得 {{0}} {{resource*}}",

    // --- 模板 ({{分类名*|sep|join}} 分类列表) ---
    "Craft {{item*|,|和}}": "制作{{item*|,|和}}",

    // --- 通用列表 {{*}} / {{*|sep|join}} ---
    "Items: {{*}}": "物品：{{*}}",
    "Mats: {{*|, |、}}": "材料：{{*|, |、}}",

    // --- 数字占位符 {{%d}} ---
    "Room {{%d}}": "房间 {{%d}}",
    "T{{%d}}": "T{{%d}}",
    "+{{0}}/s · {{1}}g": "+{{0}}/秒 · {{1}} 金币",
    "+{{0}} g/s · {{1}}g": "+{{0}} 金币/秒 · {{1}} 金币",
    "+{{0}} g/kill · {{1}}g": "+{{0}} 金币/击杀 · {{1}} 金币",
    "+{{0}}g/min · {{1}}g": "+{{0}} 金币/分钟 · {{1}} 金币",
    "+{{0}}% steal · {{1}}g": "+{{0}}% 偷取 · {{1}} 金币",
    "+{{0}}% dodge · {{1}}g": "+{{0}}% 闪避 · {{1}} 金币",
    "+{{0}}% pen · {{1}}g": "+{{0}}% 抵抗 · {{1}} 金币",
    "+×{{0}} crit · {{1}}g": "+×{{0}} 暴击 · {{1}} 金币",
    "+{{0}} DMG · {{1}}g": "+{{0}} 伤害 · {{1}} 金币",
    "+{{0}} min · {{1}}g": "+{{0}} 分钟 · {{1}} 金币",
    "+{{0}} HP · {{1}}g": "+{{0}} 生命值 · {{1}} 金币",
    "+{{0}} HP": "+{{0}} 生命值",
    "+{{0}} ARM · {{1}}g": "+{{0}} 护甲 · {{1}} 金币",
    "+{{0}}% crit · {{1}}g": "+{{0}}% 暴击 · {{1}} 金币",
    "+{{0}}% shld · {{1}}g": "+{{0}}% 护盾 · {{1}} 金币",
    "+{{0}} % · {{1}}g": "+{{0}} % · {{1}} 金币",
    "Common Copper Ring Lvl.{{%d}}": "普通 铁戒指 等级 {{%d}}",
    "Uncommon Copper Ring Lvl.{{%d}}": "罕见 铁戒指 等级 {{%d}}",
    "Uncommon Leather Cord Lvl.{{%d}}": "罕见 皮绳 等级 {{%d}}",
    "Buy {{%d}} passive upgrades": "购买 {{%d}} 被动升级",
    "Ring {{%d}}": "戒指 {{%d}}",
    "Clear {{%d}} rooms": "清理 {{%d}} 房间",
    "Defeat {{%d}} elites": "击败 {{%d}} 精英",
    "Defeat {{%d}} bosses": "击败 {{%d}} Boss",
    "Equip → Ring {{%d}}": "装备 → 戒指 {{%d}}",
    "Reach Room {{0}} in Tier {{1}}": "到达房间 {{0}} 在第 {{1}} 关中",
    "{{%d}}g": "{{%d}} 金币",
    "{{%d}}k": "{{%d}}k",
    "{{%d}}m": "{{%d}}m",
    "{{%d}}": "{{%d}}",
    "Claim +{{%d}}": "领取 +{{%d}}",
    "x{{%d}}": "x{{%d}}",
    "Uncommon Leather Pants Lvl.{{%d}}": "罕见的皮裤 等级 {{%d}}",
    "{{%d}} min": "{{%d}} 分钟",
    "HP: {{%d}}": "生命值：{{%d}}",
    "DMG: {{%d}}": "伤害：{{%d}}",

    "222":"222",
    "Exotic Verdict":"异域判决",
    "Exotic Thornwall":"异域荆棘墙",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "Nothing equipped in this slot":"此槽位未配备任何装备",
    "Arms":"胳膊",
    "Dark Knight":"暗黑骑士",
    "Neck":"项链",
    "Off-Hand":"副手",
    "SWARM ":"蜂群",
    "Bandit":"强盗",
    " Affixes":"词缀",
    "neck":"项链",
    "Area cleared — next threat incoming":"区域已肃清，新的威胁即将来袭",
    "Armor":"护甲",
    "Combat":"战斗",
    "Damage":"伤害",
    "DMG · Strike":"伤害·重击",
    "Equipped":"已装备",
    "g/kill":"每击杀收益",
    "Gear":"装备",
    "Gold":"金币",
    "Health":"生命值",
    "max":"上限",
    "Next":"下一个",
    "Passives":"被动能力",
    "Stash":"储物栏",
    "Stash empty":"储物栏为空",
    "Stats":"属性",
    "XP":"经验值",
    "Your character attacks automatically. Use the Strike button at the bottom of the screen for bonus manual damage.":"角色会自动攻击，点击屏幕底部重击按钮可额外造成手动伤害",
    "DMG":"伤害",
    "Slime":"史莱姆",
    "Items drop as you fight. Open the Gear tab to equip them and grow stronger.":"战斗中会掉落物品，前往装备界面穿戴来提升战力",
    "Begin":"开始",
    "Defeat enemies to earn Gold. Spend it in the Passives tab to permanently upgrade your power.":"击败敌人获取金币，在被动界面消耗金币永久强化自身",
    "% /kill":"击杀加成百分比",
    "% crit":"暴击率",
    "% DMG":"伤害增幅百分比",
    "% dodge":"闪避率",
    "% pen":"穿透百分比",
    "Armor Pen %":"护甲穿透百分比",
    "Attack Speed":"攻击速度",
    "crit":"暴击",
    "Crit Chance":"暴击几率",
    "Crit Damage":"暴击伤害",
    "Evasion":"闪避",
    "Gold Income":"金币收益",
    "Gold/Kill":"每击杀金币",
    "Item Armor":"装备护甲",
    "Item Damage":"装备伤害",
    "Item Health":"装备生命值",
    "Items":"物品",
    "Lifesteal":"吸血",
    "Offense":"攻击属性",
    "Offline Duration":"离线时长",
    "Offline Gold":"离线金币",
    "Shield on Kill":"击杀获护盾",
    "Strike Damage":"重击伤害",
    "Survivability":"生存能力",
    "Utility":"功能效果",
    "Goblin":"哥布林",
    "Level":"等级",
    "Ring":"戒指",
    "Sell ":"出售",
    " Max Health":"最大生命值",
    "Compare":"对比",
    "Item Stats":"物品属性",
    "Max Health":"最大生命值",
    "Sell for ":"出售可得",
    "Stat Changes":"属性变化",
    "empty slot":"空槽",
    "ring":"戒指",
    " each":" 每个",
    " Return":" 返回",
    "Abyss":"深渊",
    "Blood Moon":"血月",
    "Dark":"深色",
    "Light":"浅色",
    "Themes":"主题",
    "Shop":"商店",
    "Achievements":"成就",
    "Claim":"领取",
    "Locked":"未解锁",
    "Ascendant":"飞升者",
    "Gilded":"鎏金",
    "Oblivion":"湮灭",
    "🏆 Room 2500":"🏆 第2500层",
    "Abyss Runner":"深渊疾行者",
    "Abyss Walker":"深渊行者",
    "Blademaster":"剑术大师",
    "Bloodthirsty":"嗜血者",
    "Boss Slayer":"首领猎杀者",
    "Dedicated":"专注者",
    "Devoted":"虔信者",
    "Elite Hunter":"精英猎手",
    "Fanatic":"狂信徒",
    "Fill every gear slot":"填满所有装备栏",
    "Find your first Celestial item":"获得第一件天界装备",
    "Find your first Exotic":"获得第一件异域装备",
    "Find your first Void item":"获得第一件虚空装备",
    "Ghost":"幽魂",
    "Invested":"已投入",
    "Lucky Find":"幸运拾取",
    "Max out Attack Speed (Lv 225)":"攻击速度升至满级（225级）",
    "Max out Evasion (Lv 100)":"闪避升至满级（100级）",
    "Max out Lifesteal (Lv 100)":"吸血升至满级（100级）",
    "Max out Offline Cap (Lv 48)":"离线收益上限升至满级（48级）",
    "Milestones":"里程碑",
    "Obsessed":"痴迷者",
    "Offline King":"离线王者",
    "Passive Grinder":"被动刷取达人",
    "Repeatable":"可重复挑战",
    "Starborn":"星界之子",
    "Void-Touched":"虚空浸染者",
    "Well Equipped":"装备精良",
    " Full Wipe":"彻底重置",
    " Reset All Progress":"重置全部进度",
    "Also wipes gems and theme. Use for a true fresh start.":"同时清空宝石与外观，彻底重新开始",
    "Auto Sell":"自动出售",
    "Cloud Save":"云存档",
    "Cloud saves active":"云存档已启用",
    "Connected":"已连接",
    "Danger Zone":"危险区域",
    "Get Code":"获取码",
    "Import":"导入",
    "Items of enabled rarities are automatically sold for gold as you descend.":"下落过程中，已开启品级的物品会自动售出换取金币",
    "Move your save to another device. Generate a code here, then enter it on the other device.":"跨设备转移存档。在此生成代码，再于其他设备输入即可",
    "Permanently wipes all progress, gold, passives, gear, and stash. This cannot be undone.":"永久清除所有进度、金币、被动属性、装备及储物栏内容，操作不可撤销",
    "Save Transfer":"存档转移",
    "Unequip":"卸下装备",
    "Wolf":"狼",
    " Export Save":"导出存档",
    " Import Save":"导入存档",
    "Export your save as a code you can keep anywhere. Importing a code replaces your current progress.":"将存档导出为可保存的代码，导入代码会覆盖当前进度",
    "Local Save Backup":"本地保存备份",
    "Legs":"腿",
    "Equip":"装备",
    "Cancel":"取消",
    "Confirm":"确认",
    "Reach Tier ":"达到 T ",
    "Sell all ":"出售所有 ",
    "vs ":"vs ",
    "Chest":"胸甲",
    "Death Knight":"死亡骑士",
    "ELITE ":"精英 ",
    "Weapon":"武器",
    "Head":"头部",
    "Venomous Slime":"毒液史莱姆",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "dps":"dps",
    "Lv":"等级",
    "Lv.":"等级",
    "HP":"生命值",
    "g/s":"金币/每秒",
    "g/min offline":"金币/分钟 离线",
    "/s":"/秒",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "💎 ":"💎 ",
    "— — —":"— — —",
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    "":["",""],
    
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "关注新公众号": "关注新公众号",
    "打开微信扫一扫": "打开微信扫一扫",
    "游戏攻略交流论坛": "游戏攻略交流论坛",
    "点击加群": "点击加群",
    "锅巴汉化": "锅巴汉化",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "✓": "✓",
    "(+": "(+",
    " · +": " · +",
    " · ×": " · ×",
    "★": "★",
    "→": "→",
    "·": "·",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "设置",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',

    // --- 新增翻译 ---
    // 静态词条
    "Active Passives": "已激活被动",
    "All unlocked traits are active": "所有已解锁特性均已激活",
    "Armor %": "护甲%",
    "Armor Pen": "护甲穿透",
    "Cadence": "节奏",
    "Codex": "典籍",
    "Codex Unlocked": "典籍已解锁",
    "Counter Strike": "反击",
    "Counterstep": "反击步",
    "Crit Dmg": "暴击伤害",
    "Damage %": "伤害%",
    "Double Strike": "双重打击",
    "Dread": "恐惧",
    "Dreadmark": "恐惧印记",
    "Duality": "二元性",
    "Exotic Passive Trait": "异域被动特性",
    "Got it": "知道了",
    "Health %": "生命值%",
    "Item Tiers": "物品等级",
    "Notification": "通知",
    "Passive trait added to your Codex.": "被动特性已加入你的典籍。",
    "Thorns": "荆棘",
    "Thornwall": "荆棘之墙",
    "Trait Stash": "特性储物栏",
    "Undying Tide": "不灭潮汐",
    "Wraith": "幽魂",
    "Wraithband": "幽魂之带",
    "+1 Thorns damage per 10 Armor.": "每10点护甲+1荆棘伤害。",
    "Equip Thornwall": "装备荆棘之墙",
    "Unlocked Thornwall!": "已解锁荆棘之墙！",
    "Every 5th hit deals 35% bonus damage.": "每第5次攻击造成35%额外伤害。",
    "Every other attack strikes twice. Both hits deal 10% bonus damage on the Double Strike.": "每隔一次攻击会打击两次。两次打击均造成10%额外双重打击伤害。",
    "Gain 1 Thorns damage for every 5 Armor. When struck, the attacker takes Thorns damage (cannot kill).": "每5点护甲获得1点荆棘伤害。被击中时，攻击者受到荆棘伤害（无法致死）。",
    "Grants +10% Evasion. Upon evading an attack, deal 400% of your total Damage to the attacker.": "获得+10%闪避。闪避攻击时，对攻击者造成你总伤害400%的伤害。",
    "Grants +15% Damage. Gain an additional +15% Damage for each active Codex Passive you have equipped.": "获得+15%伤害。每装备一个已激活的典籍被动，额外获得+15%伤害。",
    "Each kill while equipped permanently grants +3 Max HP. Stacks are never lost.": "装备期间每次击杀永久获得+3最大生命值。层数永不丢失。",
    "Upon dying, immediately revive with 25% Health and gain +50% Damage for 8 seconds. Death does not rewind your progress.": "死亡时立即以25%生命值复活，并获得+50%伤害持续8秒。死亡不会回退你的进度。",
    "Dismantling Exotic items unlocks Passive Traits. Collect them in the Codex tab and equip up to 3 at once for powerful bonuses.": "分解异域物品可解锁被动特性。在典籍标签页中收集它们，最多同时装备3个以获得强力加成。",
    "All items drop at your current difficulty tier. Once you reach Tier 2 and beyond, every drop is stronger — each tier multiplies item stats by ×1.40, so a T3 item hits nearly 2× harder than a T1 equivalent. Max tier is T5.": "所有物品以当前难度等级掉落。达到等级2及以上后，每次掉落都会更强——每级将物品属性乘以×1.40，因此T3物品比同款T1强近2倍。最高等级为T5。",

    // 模板
    " Exotic Trait: {{0}}": " 异域特性：{{0}}",
    " items in stash": " 储物栏物品",
    "No {{0}}": "无{{0}}",
    "Dismantle — Unlock {{0}}": "分解 — 解锁{{0}}",
    "{{0}} Lvl.{{1}}": "{{0}} Lvl.{{1}}",
    "All 500 rooms cleared. Tier {{0}} is now unlocked.": "全部500个房间已清理。关卡 {{0}} 现已解锁。",
    "Tier {{0}} Complete!": "关卡 {{0}} 完成！",
    "Already known — sell for {{0}}g": "已习得 — 出售可得{{0}}金币",
    "Epic Chainmail Lvl.{{0}} [+{{1}} ARM, +{{2}} ARM_PEN]": "史诗 锁子甲 等级 {{0}} [+{{1}} 护甲, +{{2}} 护甲穿透]",
    "Epic Copper Ring Lvl.{{0}} [+{{1}} DMG, +{{2}} ARM_PEN]": "史诗 铜戒指 等级 {{0}} [+{{1}} 伤害, +{{2}} 护甲穿透]",
    "Epic Silver Pendant Lvl.{{0}} [+{{1}} ARM, +{{2}} CRIT_DMG]": "史诗 银吊坠 等级 {{0}} [+{{1}} 护甲, +{{2}} 暴击伤害]",
    "Epic Vitality Band Lvl.{{0}} [+{{1}} HP, +{{2}} ARM_PEN]": "史诗 活力之环 等级 {{0}} [+{{1}} 生命值, +{{2}} 护甲穿透]",
    "Epic Wooden Shield Lvl.{{0}} [+{{1}} HP, +{{2}} EVASION]": "史诗 木盾 等级 {{0}} [+{{1}} 生命值, +{{2}} 闪避]",
    "Legendary Iron Bracers Lvl.{{0}} [+{{1}} HP, +{{2}} CRIT_DMG]": "传说 铁护腕 等级 {{0}} [+{{1}} 生命值, +{{2}} 暴击伤害]",
    "Legendary Iron Helmet Lvl.{{0}} [+{{1}} DMG, +{{2}} CRIT_DMG]": "传说 铁头盔 等级 {{0}} [+{{1}} 伤害, +{{2}} 暴击伤害]",
    "Legendary Iron Shield Lvl.{{0}} [+{{1}} DMG, +{{2}} CRIT_DMG]": "传说 铁盾 等级 {{0}} [+{{1}} 伤害, +{{2}} 暴击伤害]",
    "Legendary Plate Armor Lvl.{{0}} [+{{1}} DMG, +{{2}} CRIT_DMG]": "传说 板甲 等级 {{0}} [+{{1}} 伤害, +{{2}} 暴击伤害]",
    "Legendary Silver Pendant Lvl.{{0}} [+{{1}} DMG, +{{2}} CRIT_DMG]": "传说 银吊坠 等级 {{0}} [+{{1}} 伤害, +{{2}} 暴击伤害]",
    "Legendary Wooden Shield Lvl.{{0}} [+{{1}} DMG, +{{2}} ARM_PEN]": "传说 木盾 等级 {{0}} [+{{1}} 伤害, +{{2}} 护甲穿透]",
    "Mythic Heartstone Chain Lvl.{{0}} [+{{1}} HP, +{{2}} CRIT_DMG, +{{3}} ARM_PCT]": "神话 心石链 等级 {{0}} [+{{1}} 生命值, +{{2}} 暴击伤害, +{{3}} 护甲%]",
    "Mythic Iron Shield Lvl.{{0}} [+{{1}} ARM, +{{2}} CRIT_DMG, +{{3}} ARM_PCT]": "神话 铁盾 等级 {{0}} [+{{1}} 护甲, +{{2}} 暴击伤害, +{{3}} 护甲%]",
    "Mythic Iron Sword Lvl.{{0}} [+{{1}} HP, +{{2}} ARM_PEN, +{{3}} HP_PCT]": "神话 铁剑 等级 {{0}} [+{{1}} 生命值, +{{2}} 护甲穿透, +{{3}} 生命值%]",
    "Mythic Wooden Shield Lvl.{{0}} [+{{1}} HP, +{{2}} CRIT_DMG, +{{3}} HP_PCT]": "神话 木盾 等级 {{0}} [+{{1}} 生命值, +{{2}} 暴击伤害, +{{3}} 生命值%]",
    "Mythic Wooden Shield Lvl.{{0}} [+{{1}} HP, +{{2}} ARM_PEN, +{{3}} ARM_PCT]": "神话 木盾 等级 {{0}} [+{{1}} 生命值, +{{2}} 护甲穿透, +{{3}} 护甲%]",
    "Epic Chainmail Lvl.{{0}}": "史诗 锁子甲 等级 {{0}}",
    "Epic Copper Ring Lvl.{{0}}": "史诗 铜戒指 等级 {{0}}",
    "Epic Heartstone Chain Lvl.{{0}}": "史诗 心石链 等级 {{0}}",
    "Epic Leather Armor Lvl.{{0}}": "史诗 皮甲 等级 {{0}}",
    "Epic Magic Ring Lvl.{{0}}": "史诗 魔法戒指 等级 {{0}}",
    "Epic Plate Armor Lvl.{{0}}": "史诗 板甲 等级 {{0}}",
    "Epic Silver Pendant Lvl.{{0}}": "史诗 银吊坠 等级 {{0}}",
    "Epic Steel Dagger Lvl.{{0}}": "史诗 钢匕首 等级 {{0}}",
    "Epic Tome of Power Lvl.{{0}}": "史诗 力量宝典 等级 {{0}}",
    "Epic Vitality Band Lvl.{{0}}": "史诗 活力之环 等级 {{0}}",
    "Epic Wooden Shield Lvl.{{0}}": "史诗 木盾 等级 {{0}}",
    "Legendary Iron Helmet Lvl.{{0}}": "传说 铁头盔 等级 {{0}}",
    "Mythic Heartstone Chain Lvl.{{0}}": "神话 心石链 等级 {{0}}",
    "Mythic Iron Shield Lvl.{{0}}": "神话 铁盾 等级 {{0}}",
    "Mythic Iron Sword Lvl.{{0}}": "神话 铁剑 等级 {{0}}",
    "Mythic Leather Bracers Lvl.{{0}}": "神话 皮护腕 等级 {{0}}",
    "Mythic Leather Cord Lvl.{{0}}": "神话 皮绳 等级 {{0}}",
    "Mythic Magic Ring Lvl.{{0}}": "神话 魔法戒指 等级 {{0}}",
    "Mythic Vitality Band Lvl.{{0}}": "神话 活力之环 等级 {{0}}",
    "Mythic Wooden Shield Lvl.{{0}}": "神话 木盾 等级 {{0}}",
    "Rare Heartstone Chain Lvl.{{0}} [+{{1}} DMG]": "稀有 心石链 等级 {{0}} [+{{1}} 伤害]",
    "Rare Heartstone Chain Lvl.{{0}}": "稀有 心石链 等级 {{0}}",
    " more milestone": " 更多里程碑",
    " item": " 物品",
    " pending": " 待处理",
    "ELITE {{0}}": "精英 {{0}}",
    "Reach Tier {{0}}": "到达关卡 {{0}}",
    "vs {{0}}": "对阵 {{0}}",
    "Room {{0}} — Tier {{1}}": "房间 {{0}} — 关卡 {{1}}",
    "Rare Copper Ring Lvl.{{0}}": "稀有 铜戒指 等级 {{0}}",
    "Rare Iron Greaves Lvl.{{0}} [+{{1}} ARM]": "稀有 铁护胫 等级 {{0}} [+{{1}} 护甲]",
    "Rare Tower Shield Lvl.{{0}}": "稀有 塔盾 等级 {{0}}",
    "Rare Wooden Shield Lvl.{{0}}": "稀有 木盾 等级 {{0}}",
    "Rare Leather Cord Lvl.{{0}}": "稀有 皮绳 等级 {{0}}",
    "Uncommon Amulet of Will Lvl.{{0}}": "罕见 意志护符 等级 {{0}}",
    "Uncommon Bloodstone Ring Lvl.{{0}}": "罕见 血石戒指 等级 {{0}}",
    "Uncommon Chainmail Lvl.{{0}} [+{{1}} ARM]": "罕见 锁子甲 等级 {{0}} [+{{1}} 护甲]",
    "Uncommon Heartstone Chain Lvl.{{0}}": "罕见 心石链 等级 {{0}}",
    "Uncommon Iron Dagger Lvl.{{0}}": "罕见 铁匕首 等级 {{0}}",
    "Uncommon Leather Armor Lvl.{{0}}": "罕见 皮甲 等级 {{0}}",
    "Uncommon Magic Ring Lvl.{{0}}": "罕见 魔法戒指 等级 {{0}}",
    "Uncommon Plate Armor Lvl.{{0}} [+{{1}} HP]": "罕见 板甲 等级 {{0}} [+{{1}} 生命值]",
    "Uncommon Steel Broadsword Lvl.{{0}}": "罕见 钢制阔剑 等级 {{0}}",
    "Uncommon Steel Gauntlets Lvl.{{0}}": "罕见 钢制护手 等级 {{0}}",
    "Uncommon Steel Helm Lvl.{{0}}": "罕见 钢制头盔 等级 {{0}}",
    "Uncommon Steel Legguards Lvl.{{0}}": "罕见 钢制护腿 等级 {{0}}",
    "Uncommon Wooden Shield Lvl.{{0}}": "罕见 木盾 等级 {{0}}",
    "Uncommon Rusty Sword Lvl.{{0}}": "罕见 锈剑 等级 {{0}}",
    "{{0}} hr": "{{0}} 小时",
    "{{0}} hr {{1}} min": "{{0}} 小时 {{1}} 分钟",
    "{{0}}/{{1}}": "{{0}}/{{1}}",
    "Alpha Wolf": "头狼",
    "BOSS": "首领",
    "Bandit Captain": "强盗头目",
    "Chest": "宝箱",
    "Claim Rewards": "领取奖励",
    "Colossal Golem": "巨像魔像",
    "Death Knight": "死亡骑士",
    "Done": "完成",
    "Dragon of the Abyss": "深渊巨龙",
    "Enjoying Abyss?": "喜欢深渊吗？",
    "Head": "头盔",
    "Lich King": "巫妖王",
    "Orc Warlord": "兽人督军",
    "Rate ★": "评价 ★",
    "Skeleton": "骷髅兵",
    "Skeleton Champion": "骷髅勇士",
    "Tier Complete": "关卡完成",
    "Venomous Slime": "毒液史莱姆",
    "Weapon": "武器",
    "chest": "胸甲",
    "head": "头盔",
    "mainWeapon": "主武器",
    "offHand": "副手",
    "A rating on itch.io helps the game more than you know.": "在itch.io上给个好评，对游戏帮助超乎你想象。",


};
// ============================================================
// cnResourceNames — 资源名词翻译（备用，优先级低于 cnItems）
// ============================================================
// 支持 "名词: 数值" 格式的自动翻译（如 "Mana: 500" → "法力：500"）
var cnResourceNames = {};
// cnRegReplace — 正则替换（备用，优先级低于精确匹配但高于模板/分类）
var cnRegReplace = new Map([]);
// 前缀/后缀提取（备用）
var cnPrefix = {};
var cnPostfix = {};
// 排除规则（备用）
var cnExcludeWhole = [];
var cnExcludePostfix = [];
